spring.application.name=nextset
server.port=8080

# --- CONFIGURAÇÃO H2 (Exclusiva desta Branch) ---
spring.datasource.url=jdbc:h2:mem:nextset_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console H2 e DDL
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Segurança (Use uma chave de teste aqui, já que é branch de dev)
api.security.token.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

# --- GOOGLE OAUTH CONFIG ---
# O ID é público, mas vamos usar variável por boa prática
google.client.id=${GOOGLE_CLIENT_ID:853127303458-fgpgjsqjbdiijjl0n7ubmill7am7haif.apps.googleusercontent.com}

# O SECRET é ABSOLUTAMENTE SECRETO. Nunca coloque o valor real aqui.
google.client.secret=${GOOGLE_CLIENT_SECRET:TROCAR_CHAVE_SECRETA_DO_GOOGLE}

# A URL de redirecionamento pode ficar fixa, pois é configuração local/prod
google.redirect.uri=http://localhost:4200/login